apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
        - name: currency
          image: gcr.io/fiery-iridium-235312/test/currency:9
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP