workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - publish-docker:
          requires:
            - unit-test
          filters:
            branches:
              only: master

version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - currency-{{ checksum "pom.xml" }}
            - currency
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: currency-{{ checksum "pom.xml" }}
      - run:
          name: Build and unit test
          command: |
            mvn test
      - store_test_results:
          path: target/surefire-reports


  publish-docker:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - currency-{{ checksum "pom.xml" }}
            - currency
      - run:
          name: Login to docker repo
          command: docker login -u _json_key -p "$GOOGLE_AUTH" https://gcr.io
      - run:
          name: Build image
          command: |
            mvn compile jib:build -DskipTests=true \
              -Dbuild.number=${CIRCLE_BUILD_NUM}
      - run:
          name: send echo when finish
          command: |
            echo success!



#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#      - unit-test
#      - say-hello:
#          requires:
#            - unit-test
#
#version: 2
#jobs:
#  unit-test:
#    docker:
#      - image: circleci/openjdk:11-jdk
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - run: mvn dependency:go-offline
#      - run:
#          name: Build and unit test
#          command: |
#            mvn test
#
#  say-hello:
#    docker:
#      - image: circleci/node:4.8.2
#    working_directory: ~/repo
#    steps:
#      - checkout
#      - run:
#          name: Say Hello
#          command: |
#            echo Hello